name: Build with Buck

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build our program
      id: build
      uses: SandakovMM/build-with-buck@v3
      with:
        command: build
        target: :result
    - name: Store result
      uses: actions/upload-artifact@v3
      with:
        name: mylittleprogramm
        path: ./buck-out/gen/result.pex
